name: Pipeline 1
on: push
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Import Code
        uses: actions/checkout@v4
      - name: Run Script
        run: python script_test.py
